import { describe, expect, it } from "vitest";
import { TestDriver } from "testdriverai/vitest/hooks";

/**
 * SEC-1 regression guard — the player secret must NEVER travel in a URL.
 *
 * Issue #105 (SEC-1): the per-player credential (`player_secret`) is currently
 * exposed via URL query params (and can therefore land in server access logs,
 * browser history, the Referer header, proxy logs, and console/error strings).
 * The two source-of-truth leak sites in the frontend today are:
 *
 *   1. src/services/gameSocket.ts — getWsUrl() falls back to
 *        url.searchParams.set('secret', playerSecret)
 *        url.searchParams.set('player_id', playerId)
 *      whenever there is no stored JWT access token, so the WebSocket handshake
 *      URL is  ws://host/ws/game/<room>/?secret=<PLAYER_SECRET>&player_id=<id> .
 *
 *   2. src/services/api.ts — the Discord account-status GET builds
 *        /auth/discord/status/?player_id=<id>&player_secret=<PLAYER_SECRET>
 *
 * The fix (SEC-1) moves the secret off the URL and into the Authorization
 * header / POST body / first WebSocket message. Once that lands, the secret no
 * longer appears in ANY request URL and this test goes green.
 *
 * How this test proves it (real stack, real browser, real network):
 *   - Boots the SAME stack the e2e workflow uses inside the TestDriver sandbox:
 *     Redis + a natively-booted Django backend (daphne :8000) + the Vite
 *     frontend (:8081). No mocking — the real gameSocket.ts / api.ts run.
 *   - Drives create-room through the real UI in Chrome, which puts the player
 *     into a room and triggers gameSocket.connect() (the vulnerable path).
 *   - Records EVERY network request URL the browser issued (HTTP + WebSocket)
 *     via Chrome's remote debugging protocol, plus the browser console output.
 *   - Asserts the freshly-minted player secret appears in NONE of those URLs
 *     and in NO console/error line.
 *
 * This is a RED regression guard: on `main` (and on this branch until SEC-1 is
 * implemented) it FAILS because the secret is in the WebSocket URL. It is the
 * gate for issue #105 — do not weaken it to make it pass; fix the leak instead.
 *
 * Target selection: this test boots its own stack in the sandbox, so it needs
 * no external deployment (unlike the smoke suite's SOUND_ROYALE_URL). The repo
 * checkout is copied into the sandbox so the REAL frontend/backend source runs.
 */

// The frontend dev server port. Must match the CORS-allowed origins the backend
// is booted with below and the port Vite is told to listen on.
const FRONTEND_PORT = 8099;
const BACKEND_PORT = 8098;
const FRONTEND_URL = `http://localhost:${FRONTEND_PORT}`;
const BACKEND_URL = `http://localhost:${BACKEND_PORT}`;

// A distinctive marker we can grep for. The real secret is generated by the
// backend at room-creation time; we capture it from the create-room response
// rather than guessing it, so the assertion is exact.
const CHROME_DEBUG_PORT = 9222;

// base64 so multi-line scripts drop into a single exec without heredoc/quoting
// fragility (same technique as tests/testdriver/health-redis-down.test.mjs).
const b64 = (s) => Buffer.from(s, "utf8").toString("base64");

// Node script (run inside the sandbox) that drives create-room via the browser
// and records network URLs + console output through the Chrome DevTools
// Protocol. It talks to the already-running Chrome over its remote-debugging
// port, so it observes the exact traffic the real app produces — including the
// WebSocket handshake URL, which is where SEC-1 currently leaks the secret.
const CDP_CAPTURE_JS = `
const CDP = require('chrome-remote-interface');
const FRONTEND_URL = ${JSON.stringify(FRONTEND_URL)};
const PORT = ${CHROME_DEBUG_PORT};

const requestUrls = [];
const consoleLines = [];

function record(url) {
  if (typeof url === 'string' && url.length) requestUrls.push(url);
}

(async () => {
  const client = await CDP({ port: PORT });
  const { Network, Page, Runtime, Target } = client;
  await Network.enable();
  await Page.enable();
  await Runtime.enable();

  // Capture every HTTP(S) request URL and every WebSocket handshake URL.
  Network.requestWillBeSent((p) => record(p.request && p.request.url));
  Network.webSocketCreated((p) => record(p.url));
  Network.webSocketWillSendHandshakeRequest((p) => record(p.url));

  // Capture console + page errors (SEC-1 also forbids the secret in
  // console/error strings).
  Runtime.consoleAPICalled((e) => {
    consoleLines.push((e.args || []).map((a) => a.value ?? a.description ?? '').join(' '));
  });
  Runtime.exceptionThrown((e) => {
    consoleLines.push(JSON.stringify(e.exceptionDetails || {}));
  });

  const runId = Date.now().toString().slice(-6);

  await Page.navigate({ url: FRONTEND_URL + '/' });
  await Page.loadEventFired();

  // Suppress the onboarding modal that blocks the name input, then create a
  // room entirely through the app so the REAL gameSocket.connect() fires.
  const evalJs = async (expression) =>
    (await Runtime.evaluate({ expression, awaitPromise: true, returnByValue: true })).result.value;

  await evalJs("localStorage.setItem('hasSeenOnboarding','true'); location.reload();");
  await new Promise((r) => setTimeout(r, 2500));

  // Drive create-room via the same data-testids the live e2e specs use.
  const created = await evalJs(\`(async () => {
    const q = (id) => document.querySelector('[data-testid="' + id + '"]');
    const setVal = (el, v) => {
      const proto = Object.getPrototypeOf(el);
      const desc = Object.getOwnPropertyDescriptor(proto, 'value');
      desc.set.call(el, v);
      el.dispatchEvent(new Event('input', { bubbles: true }));
    };
    const nameInput = q('player-name-input');
    if (!nameInput) return 'NO_NAME_INPUT';
    setVal(nameInput, 'Host${'$'}{Math.random().toString(36).slice(2,8)}');
    await new Promise((r) => setTimeout(r, 200));
    q('create-room-button')?.click();
    await new Promise((r) => setTimeout(r, 400));
    const roomName = q('create-room-name-input');
    if (roomName) setVal(roomName, 'SEC1 Room');
    await new Promise((r) => setTimeout(r, 200));
    q('create-room-submit-button')?.click();
    return 'SUBMITTED';
  })()\`);

  // Wait for navigation into /room/<code> and for the WebSocket to connect.
  await new Promise((r) => setTimeout(r, 6000));

  // Pull the freshly-minted player secret straight out of the app's session
  // storage so the assertion is exact (the backend generated it; we don't guess).
  const secret = await evalJs(\`(() => {
    try {
      const scan = (store) => {
        for (let i = 0; i < store.length; i++) {
          const k = store.key(i);
          const v = store.getItem(k);
          if (!v) continue;
          const m = v.match(/"?player[_]?[Ss]ecret"?\\\\s*[:=]\\\\s*"([^"]+)"/);
          if (m) return m[1];
          try {
            const o = JSON.parse(v);
            if (o && (o.playerSecret || o.player_secret)) return o.playerSecret || o.player_secret;
          } catch {}
        }
        return null;
      };
      return scan(localStorage) || scan(sessionStorage) || null;
    } catch { return null; }
  })()\`);

  const finalUrl = await evalJs('location.href');

  console.log('CAPTURE_JSON=' + JSON.stringify({
    createStatus: created,
    secret: secret,
    finalUrl: finalUrl,
    requestUrls,
    consoleLines,
  }));

  await client.close();
  process.exit(0);
})().catch((err) => {
  console.error('CDP_CAPTURE_ERROR=' + (err && err.stack || String(err)));
  process.exit(1);
});
`;

describe("SEC-1 (#105): player secret must never appear in a URL", () => {
  it("does not leak player_secret in any request URL or console output", async (context) => {
    const testdriver = TestDriver(context);

    // Provision Chrome WITH a remote-debugging port so the CDP capture script
    // can attach and observe real network traffic.
    await testdriver.provision.chrome({
      url: "about:blank",
      args: [`--remote-debugging-port=${CHROME_DEBUG_PORT}`],
    });

    // ---------------------------------------------------------------------
    // 1) Boot the real stack inside the sandbox: Redis + Django (daphne) +
    //    Vite frontend. The repo checkout is available at /workspace.
    // ---------------------------------------------------------------------
    const boot = await testdriver.exec(
      "sh",
      [
        "set -e",
        "cd /workspace",
        // Redis for the Channels layer (real WebSocket path).
        "redis-server --daemonize yes --port 6379 || (nohup redis-server --port 6379 >/tmp/redis.log 2>&1 &)",
        // --- Backend ---
        "cd backend",
        "python3 -m venv venv 2>/dev/null || true",
        ". venv/bin/activate",
        "pip install --quiet -r requirements.txt",
        "mkdir -p logs",
        "export SECRET_KEY=sec1-ci-secret-not-for-production",
        "export DEBUG=True",
        "export DJANGO_SETTINGS_MODULE=sound_royale_api.settings",
        `export ALLOWED_HOSTS=localhost,127.0.0.1,testserver,localhost:${BACKEND_PORT}`,
        `export CORS_ALLOWED_ORIGINS=${FRONTEND_URL}`,
        `export CSRF_TRUSTED_ORIGINS=${FRONTEND_URL}`,
        "export REDIS_URL=redis://localhost:6379/0",
        "python manage.py migrate --noinput",
        `nohup python -m daphne -p ${BACKEND_PORT} -b 0.0.0.0 sound_royale_api.asgi:application > /tmp/backend.log 2>&1 &`,
        // --- Frontend ---
        "cd /workspace",
        `export VITE_API_BASE_URL=${BACKEND_URL}/api`,
        `nohup npm run dev:frontend -- --port ${FRONTEND_PORT} --host > /tmp/frontend.log 2>&1 &`,
        // --- Wait for both to answer ---
        `for i in $(seq 1 60); do curl -s -o /dev/null ${BACKEND_URL}/api/health/ && break; sleep 2; done`,
        `for i in $(seq 1 60); do curl -s -o /dev/null ${FRONTEND_URL}/ && break; sleep 2; done`,
        `echo BACKEND=$(curl -s -o /dev/null -w '%{http_code}' ${BACKEND_URL}/api/health/)`,
        `echo FRONTEND=$(curl -s -o /dev/null -w '%{http_code}' ${FRONTEND_URL}/)`,
        "echo BOOT_DONE",
      ].join("\n"),
      600000,
    );
    const bootOut = String(boot?.stdout ?? boot ?? "");
    console.log("Stack boot output:\n" + bootOut);
    expect(bootOut, "stack failed to boot").toContain("BOOT_DONE");
    expect(bootOut, "backend never became reachable").toMatch(/BACKEND=200/);
    expect(bootOut, "frontend never became reachable").toMatch(/FRONTEND=200/);

    // ---------------------------------------------------------------------
    // 2) Run the CDP capture: create a room via the real UI and record every
    //    request URL + console line the browser produced.
    // ---------------------------------------------------------------------
    const cap = await testdriver.exec(
      "sh",
      [
        "set -e",
        "cd /tmp",
        `echo ${b64(CDP_CAPTURE_JS)} | base64 -d > /tmp/sec1-capture.cjs`,
        // chrome-remote-interface is a tiny, dependency-free CDP client.
        "npm install --no-save --silent chrome-remote-interface >/tmp/npm-cri.log 2>&1 || true",
        "node /tmp/sec1-capture.cjs",
      ].join("\n"),
      180000,
    );
    const capOut = String(cap?.stdout ?? cap ?? "");
    console.log("CDP capture output:\n" + capOut);

    const jsonLine = (capOut.match(/CAPTURE_JSON=(\{[\s\S]*\})\s*$/m) || [])[1];
    expect(jsonLine, `CDP capture did not emit CAPTURE_JSON. Output:\n${capOut}`).toBeTruthy();

    const capture = JSON.parse(jsonLine);
    console.log("Create status:", capture.createStatus);
    console.log("Final URL:", capture.finalUrl);
    console.log("Captured request URLs:\n" + capture.requestUrls.join("\n"));

    // We must actually have entered a room and captured a WebSocket connection,
    // otherwise the test would vacuously pass without exercising the leak path.
    expect(
      capture.createStatus,
      "create-room UI flow did not submit — cannot assert on the WS URL",
    ).toBe("SUBMITTED");
    expect(
      capture.finalUrl,
      "browser never navigated into a /room/<code> — room creation flow broke",
    ).toMatch(/\/room\/\d+/);
    expect(
      capture.requestUrls.some((u) => u.startsWith("ws://") || u.startsWith("wss://")),
      "no WebSocket connection was observed — the vulnerable path never ran",
    ).toBe(true);

    // We captured the real secret out of the app's own storage.
    const secret = capture.secret;
    expect(
      secret && String(secret).length >= 8,
      `could not recover the player secret from app storage (got: ${secret})`,
    ).toBe(true);

    // === SEC-1 contract (the gate for #105) ===
    // The secret must not appear in ANY request URL (query string or path) …
    const leakingUrls = capture.requestUrls.filter((u) => u.includes(secret));
    expect(
      leakingUrls,
      `SEC-1 VIOLATION: player secret leaked in request URL(s):\n${leakingUrls.join("\n")}\n` +
        `Move the secret off the URL into the Authorization header / POST body / ` +
        `first WebSocket message (issue #105).`,
    ).toEqual([]);

    // … and it must not appear in any console / error line.
    const leakingConsole = (capture.consoleLines || []).filter((l) => l.includes(secret));
    expect(
      leakingConsole,
      `SEC-1 VIOLATION: player secret leaked in console/error output:\n${leakingConsole.join("\n")}`,
    ).toEqual([]);
  });
});
