# Generated by Django 5.2.9 on 2025-12-31 16:49

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('is_spectator', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['joined_at'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('lobby', 'Lobby'), ('playing', 'Playing'), ('finished', 'Finished')], default='lobby', max_length=20)),
                ('current_round', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_rooms', to='game_engine.player')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='player',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game_engine.room'),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('room', 'name')},
        ),
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('genre', models.CharField(choices=[('phonk', 'Phonk'), ('trap', 'Trap'), ('lofi', 'Lo-Fi'), ('house', 'House'), ('drill', 'Drill'), ('rnb', 'R&B'), ('edm', 'EDM'), ('jazz', 'Jazz'), ('ambient', 'Ambient')], max_length=20)),
                ('status', models.CharField(choices=[('empty', 'Empty'), ('pending', 'Pending'), ('complete', 'Complete')], default='empty', max_length=20)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg', 'm4a'])])),
                ('audio_url', models.URLField(blank=True, null=True)),
                ('position', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiles', to='game_engine.player')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('player', 'position')},
            },
        ),
    ]
