# Generated by Django 5.2.9 on 2026-01-07 17:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_secret',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
