# Generated by Django 5.2.9 on 2026-01-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_engine', '0002_player_player_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_connected',
            field=models.BooleanField(default=False),
        ),
    ]
