# Generated by Django 4.2.7 on 2026-02-18 00:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('game_engine', '0005_add_room_to_tile'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='elo_losses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='elo_matches',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='elo_rating',
            field=models.PositiveIntegerField(default=1200),
        ),
        migrations.AddField(
            model_name='player',
            name='elo_wins',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(blank=True, default='', max_length=4, unique=True),
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('round_number', models.PositiveIntegerField(default=1)),
                ('current_tile_genre', models.CharField(choices=[('phonk', 'Phonk'), ('trap', 'Trap'), ('lofi', 'Lo-Fi'), ('house', 'House'), ('drill', 'Drill'), ('rnb', 'R&B'), ('edm', 'EDM'), ('jazz', 'Jazz'), ('ambient', 'Ambient')], max_length=20)),
                ('timer_duration', models.PositiveIntegerField(default=60)),
                ('timer_started_at', models.DateTimeField(blank=True, null=True)),
                ('timer_ends_at', models.DateTimeField(blank=True, null=True)),
                ('voting_open', models.BooleanField(default=False)),
                ('votes_recorded', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='game_engine.room')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_rounds', to='game_engine.player')),
            ],
            options={
                'ordering': ['-round_number'],
                'unique_together': {('room', 'round_number')},
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='game_engine.round')),
                ('voted_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_received', to='game_engine.player')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_cast', to='game_engine.player')),
            ],
            options={
                'unique_together': {('round', 'voter')},
            },
        ),
    ]
