# Generated by Django 4.2.7 on 2026-02-20 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_engine', '0006_voting_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_host',
            field=models.BooleanField(default=False),
        ),
    ]
