# Generated by Django 4.2.7 on 2026-04-30 15:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('game_engine', '0009_emailverificationcode_verifieduser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EloDeltaEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_elo', models.PositiveIntegerField()),
                ('delta', models.IntegerField()),
                ('new_elo', models.PositiveIntegerField()),
                ('match_result', models.CharField(max_length=10)),
                ('reason', models.CharField(max_length=50)),
                ('idempotency_key', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elo_deltas', to='game_engine.room')),
                ('verified_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elo_deltas', to='game_engine.verifieduser')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['verified_user', '-created_at'], name='game_engine_verifie_be397b_idx'), models.Index(fields=['idempotency_key'], name='game_engine_idempot_aa56aa_idx')],
            },
        ),
    ]
