# Generated by Codex on 2026-05-04

from django.db import migrations, models


DEFAULT_ROTATIONS = {
    "classic": {
        "name": "Classic",
        "description": "theme by @1120cooks",
        "genres": ["Phonk", "Trap", "Lo-Fi", "House", "Drill", "R&B", "EDM", "Jazz", "Ambient"],
    },
    "weekly": {
        "name": "Weekly Rotation",
        "description": "theme by @1120cooks",
        "genres": ["Trap", "Phonk", "Drill", "R&B", "EDM", "House", "Lo-Fi", "Jazz", "Ambient"],
    },
    "monthly": {
        "name": "Monthly Rotation",
        "description": "theme by @1120cooks",
        "genres": ["House", "EDM", "Techno", "Disco", "Lo-Fi", "R&B", "Trap", "Phonk", "Ambient"],
    },
}


def seed_theme_rotations(apps, schema_editor):
    ThemeRotation = apps.get_model("game_engine", "ThemeRotation")
    for key, data in DEFAULT_ROTATIONS.items():
        ThemeRotation.objects.update_or_create(key=key, defaults=data)


def remove_theme_rotations(apps, schema_editor):
    ThemeRotation = apps.get_model("game_engine", "ThemeRotation")
    ThemeRotation.objects.filter(key__in=DEFAULT_ROTATIONS.keys()).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("game_engine", "0009_add_is_ready_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="theme",
            field=models.CharField(
                blank=True,
                choices=[
                    ("classic", "Classic"),
                    ("weekly", "Weekly Rotation"),
                    ("monthly", "Monthly Rotation"),
                    ("phonk", "Phonk"),
                    ("trap", "Trap"),
                    ("lofi", "Lo-Fi"),
                    ("house", "House"),
                    ("electronic", "Electronic"),
                    ("custom", "Custom"),
                ],
                default="classic",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ThemeRotation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(choices=[("classic", "Classic"), ("weekly", "Weekly Rotation"), ("monthly", "Monthly Rotation")], max_length=20, unique=True)),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(default="theme by @1120cooks", max_length=120)),
                ("genres", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["key"],
            },
        ),
        migrations.RunPython(seed_theme_rotations, remove_theme_rotations),
    ]
