# Generated by Codex on 2026-05-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_engine", "0010_theme_rotation"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="is_checked_in",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="player",
            name="earned_jackpot",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="player",
            name="earned_sweeper",
            field=models.BooleanField(default=False),
        ),
    ]
