# Generated by Django 4.2.7 on 2026-04-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_engine', '0010_elodeltaevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='EloIdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['key'], name='game_engine_key_926222_idx'), models.Index(fields=['expires_at'], name='game_engine_expires_db6fa5_idx')],
            },
        ),
    ]
