# Generated by Django 4.2.7 on 2026-04-30 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_engine', '0011_eloidempotencykey'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.CharField(max_length=100, unique=True)),
                ('discord_username', models.CharField(max_length=100)),
                ('discord_avatar', models.CharField(blank=True, max_length=100, null=True)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discord_identity', to='game_engine.verifieduser')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['discord_id'], name='game_engine_discord_849a6a_idx')],
            },
        ),
    ]
