# Generated by Django 4.2.7 on 2026-05-07 15:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('game_engine', '0011_player_title_flags'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discord_user_id', models.CharField(max_length=255, unique=True)),
                ('discord_username', models.CharField(blank=True, max_length=255)),
                ('discord_avatar_url', models.TextField(blank=True, null=True)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('privacy_settings', models.JSONField(blank=True, default=dict)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discord_account', to='game_engine.player')),
            ],
            options={
                'unique_together': {('player', 'discord_user_id')},
            },
        ),
        migrations.CreateModel(
            name='DiscordServer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('server_id', models.CharField(max_length=255, unique=True)),
                ('server_name', models.CharField(blank=True, max_length=255)),
                ('bot_added_at', models.DateTimeField(auto_now_add=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='DiscordServerMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('elo_tier', models.CharField(blank=True, max_length=50)),
                ('roles', models.JSONField(blank=True, default=list)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('discord_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_memberships', to='game_engine.discordaccount')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='game_engine.discordserver')),
            ],
            options={
                'unique_together': {('server', 'discord_account')},
            },
        ),
    ]
