# Generated by Django 4.2.7 on 2026-04-30 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_engine', '0012_discordidentity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='elo_losses',
        ),
        migrations.RemoveField(
            model_name='player',
            name='elo_matches',
        ),
        migrations.RemoveField(
            model_name='player',
            name='elo_rating',
        ),
        migrations.RemoveField(
            model_name='player',
            name='elo_wins',
        ),
    ]
