# Generated by Codex on 2026-05-08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("game_engine", "0012_discordaccount_discordserver_discordservermember"),
    ]

    operations = [
        migrations.AddField(
            model_name="discordaccount",
            name="session_secret",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="player",
            name="discord_identity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_players",
                to="game_engine.discordaccount",
            ),
        ),
    ]
