# Generated by Django 4.2.7 on 2026-04-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_engine', '0013_remove_player_elo_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='bonus_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='room',
            name='custom_genres',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='room',
            name='is_rotational',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='theme',
            field=models.CharField(blank=True, choices=[('classic', 'Classic'), ('phonk', 'Phonk Heavy'), ('trap', 'Trap'), ('lofi', 'Chill Vibes'), ('house', 'Electronic'), ('custom', 'Custom')], default='classic', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='total_rounds',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
