# Generated by Django 4.2.7 on 2026-05-28 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_engine', '0013_stable_discord_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game_engine.room'),
        ),
    ]
