# Generated by Django 4.2.7 on 2026-04-30 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_engine', '0014_room_bonus_multiplier_room_custom_genres_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_rotational',
        ),
    ]
