# Generated by Django 4.2.7 on 2026-06-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_engine', '0015_player_user_alter_tile_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='match_type',
            field=models.CharField(choices=[('casual', 'Casual'), ('ranked', 'Ranked')], default='casual', max_length=10),
        ),
    ]
