# Generated by Django 4.2.7 on 2026-04-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_engine', '0015_remove_is_rotational'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='total_rounds',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
