# Generated by Django 4.2.7 on 2026-07-14 12:18

from django.db import migrations, models
import game_engine.security


def hash_existing_secrets(apps, schema_editor):
    """Re-hash any existing plaintext secrets (guardrail #105).

    Pre-existing rows stored a plaintext UUID; after the column change they
    are no longer valid credentials. Regenerate a fresh hash for each player,
    invalidating prior sessions (rooms are ephemeral, no real users yet).
    """
    Player = apps.get_model("game_engine", "Player")
    for player in Player.objects.all():
        # Only re-hash rows that are still plaintext (not a 64-hex digest).
        if not game_engine.security.is_hex64(player.player_secret):
            player.player_secret = game_engine.security.new_player_secret()
            player.save(update_fields=["player_secret"])


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('game_engine', '0016_add_match_type_to_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_secret',
            field=models.CharField(default=game_engine.security.new_player_secret, editable=False, max_length=64),
        ),
        migrations.RunPython(hash_existing_secrets, reverse_noop),
    ]
