# Generated by Django 4.2.7 on 2026-07-12 23:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('game_engine', '0016_add_match_type_to_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='BingoClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bingo_claims', to='game_engine.player')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bingo_claims', to='game_engine.room')),
            ],
            options={
                'unique_together': {('room', 'player')},
            },
        ),
    ]
