# Generated by Django 4.2.7 on 2026-07-19 12:14

from django.db import migrations, models
import game_engine.security


class Migration(migrations.Migration):

    dependencies = [
        ('game_engine', '0017_bingoclaim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_secret',
            field=models.CharField(default=game_engine.security.new_player_secret, editable=False, max_length=64),
        ),
    ]
